version: '3.4'
services:
  projeto_challenge:
    image: projeto_challenge
    build: .
    ports:
      - "5103:8080"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"