services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: projetochallengedb
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "A@VeryStrongP4ssword!"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P A@VeryStrongP4ssword! -Q 'SELECT 1' || exit 1"]
      interval: 15s
      retries: 10
      start_period: 60s
    networks:
      - challengenetwork

  projeto_challenge:
    image: projeto_challenge
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5103:8080"
    depends_on:
      - sqlserver
    networks:
      - challengenetwork

  projeto_challenge_frontend:
    image: projeto_challenge_frontend
    build:
      context: ./frontend-application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - projeto_challenge
    networks:
      - challengenetwork


networks:
  challengenetwork:
    driver: bridge